[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fossr = "5WCXWwsaw8WRxMzxqBiAQ5ByHWY9ruV9egijtgC493SP"

[programs.devnet]
fossr = "5WCXWwsaw8WRxMzxqBiAQ5ByHWY9ruV9egijtgC493SP"

[programs.mainnet]
fossr = "5WCXWwsaw8WRxMzxqBiAQ5ByHWY9ruV9egijtgC493SP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=e8cb713e-06f4-48e3-9248-2feb452aff7d"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
